version: "3"
services:
  arch:
    build: .
    volumes:
      - .:/app
    links:
      - redis_arch:redishost
    ports:
      - "9292:9292"
    environment:
      - REDIS_ADDRESS=http://redishost:6379
      - APP_NAME=arch
    command: ./scripts/start.sh arch
    # http://dockerhost:9292
  getit:
    build: .
    volumes:
      - .:/app
    links:
      - redis_getit:redishost
    environment:
      - REDIS_ADDRESS=http://redishost:6379
      - APP_NAME=getit
    ports:
      - "9293:9292"
    command: ./scripts/start.sh getit
    # http://dockerhost:9293
  redis_arch:
    build: ./redis
  redis_getit:
    build: ./redis
