version: "3.2"
services:

  arch:
    image: salon_arch
    build:
      context: .
      cache_from:
        - ruby:2.5.1-alpine
        - salon_arch
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    environment:
      - REDIS_HOST=http://redis_arch:6379
      - APP_NAME=arch
    env_file:
      - secrets.env
    command: "./scripts/start.sh arch"
    depends_on:
      - redis

  test:
    image: salon_test
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - ruby:2.5.1-alpine
        - salon_test
    environment:
      REDIS_HOST: http://redis_test:6379
      TEST_CLIENT_ID:
      TEST_CLIENT_SECRET:
      COVERALLS_REPO_TOKEN:
      CI:
    env_file:
      - secrets.env
    command: "bundle exec rake"
    depends_on:
      - test_redis

  test_redis:
    image: redis:3-alpine

  redis:
    image: redis:3-alpine
