version: "3"
services:
  arch:
    build: .
    volumes:
      - .:/app
    links:
      - redis_arch:redishost
    ports:
      - "9292:9292"
    environment:
      - REDIS_ADDRESS=http://redishost:6379
    command: ./scripts/start.sh
    # http://dockerhost:9292
  getit:
    build: .
    volumes:
      - .:/app
    links:
      - redis_getit:redishost
    environment:
      - REDIS_ADDRESS=http://redishost:6379
    ports:
      - "9293:9292"
    command: ./scripts/start.sh
    # http://dockerhost:9293
  redis_arch:
    build: ./redis
    expose:
      - "6379"
  redis_getit:
    build: ./redis
    expose:
      - "6379"
