version: "3.2"
services:

  arch:
    build: .
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    environment:
      - REDIS_HOST=http://redis_arch:6379
      - APP_NAME=arch
    env_file:
      - secrets.env
    # command: rackup -o 0.0.0.0
    command: "tail -f /dev/null"
    depends_on:
      - redis_arch

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      REDIS_HOST: http://redis_test:6379
      TEST_CLIENT_ID:
      TEST_CLIENT_SECRET:
      COVERALLS_REPO_TOKEN:
      CI:
    env_file:
      - secrets.env
    command: "tail -f /dev/null"
    depends_on:
      - redis_test

  redis_test:
    image: redis:3-alpine

  redis_arch:
    image: redis:3-alpine
