version: "2"
services:

  arch:
    build: .
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    environment:
      - REDIS_HOST=http://redis_arch:6379
      - APP_NAME=arch
    env_file:
      - secrets.env
    command: ./scripts/start.sh arch
    depends_on:
      - redis_arch
    # http://dockerhost:9292

  getit:
    build: .
    volumes:
      - .:/app
    links:
      - redis_getit:redishost
    environment:
      - REDIS_HOST=http://redis_getit:6379
      - APP_NAME=getit
    env_file:
      - secrets.env
    ports:
      - "9293:9292"
    command: ./scripts/start.sh getit
    depends_on:
      - redis_getit
    # http://dockerhost:9293

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=http://redis_test:6379
    command: "tail -f /dev/null"
    depends_on:
      - redis_test

  redis_test:
    build: ./redis

  redis_getit:
    build: ./redis
    image: nyulibraries/salon_redis

  redis_arch:
    build: ./redis
    image: nyulibraries/salon_redis
