app:
  build: .
  volumes:
    - .:/salon
  links:
    - redis:redishost
  expose:
    - "80"
redis:
  image: redis
  expose:
    - "6379"
web:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - app
