version: "3"
services:

  getit:
    image: nyulibraries/salon
    networks:
      redis_getit:
        aliases:
          - redishost
    environment:
      - REDIS_ADDRESS=http://redishost:6379
      - APP_NAME=getit
    env_file:
      - secrets.env
    ports:
      - "8080:8080"
    command: "./scripts/start.sh getit production"
    deploy:
      mode: replicated
      replicas: 2

  arch:
    image: nyulibraries/salon
    networks:
      redis_arch:
        aliases:
          - redishost
    environment:
      - REDIS_ADDRESS=http://redishost:6379
      - APP_NAME=arch
    env_file:
      - secrets.env
    ports:
      - "8081:8080"
    command: "./scripts/start.sh arch production"
    deploy:
      mode: replicated
      replicas: 2

  redis_getit:
    image: nyulibraries/salon_redis
    ports:
      - "6378:6379"
    networks:
      - redis_getit

  redis_arch:
    image: nyulibraries/salon_redis
    ports:
      - "6379:6379"
    networks:
      - redis_arch

  nginx:
    image: nyulibraries/salon_nginx
    networks:
      getit:
        aliases:
          - getit
      arch:
        aliases:
          - arch
    ports:
      - "8001:80"
    deploy:
      mode: replicated
      replicas: 6

networks:
  redis_getit:
  redis_arch:
  getit:
  arch:
