version: "3"
services:
  getit:
    build: .
    links:
      - redis_getit:redishost
    expose:
      - "8080"
    command: "scripts/start.sh"
    deploy:
      mode: replicated
      replicas: 2
  arch:
    build: .
    links:
      - redis_arch:redishost
    expose:
      - "8081"
    command: "scripts/start.sh"
    deploy:
      mode: replicated
      replicas: 2
  redis_getit:
    image: redis
    expose:
      - "6379"
  redis_arch:
    build: ./redis
    expose:
      - "6379"
  web:
    build: ./nginx
    ports:
      - "8001:80"
    links:
      - getit
      - arch
    deploy:
      mode: replicated
      replicas: 6
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s
