version: "3"
services:
  getit:
    build: .
    links:
      - redis_getit:redishost
    environment:
      - REDIS_ADDRESS=http://redishost:6379
      - APP_NAME=getit
    command: "./scripts/start.sh getit production"
    deploy:
      mode: replicated
      replicas: 2
  arch:
    build: .
    links:
      - redis_arch:redishost
    environment:
      - REDIS_ADDRESS=http://redishost:6379
      - APP_NAME=arch
    command: "./scripts/start.sh arch production"
    deploy:
      mode: replicated
      replicas: 2
  redis_getit:
    build: ./redis
  redis_arch:
    build: ./redis
  nginx:
    build: ./nginx
    links:
      - getit
      - arch
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 6
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s
