app:
  build: .
  volumes:
    - .:/app
  links:
    - redis:redishost
  ports:
    - "8080:8080"
  # volumes:
    # - data-volume:/app
  command: ./scripts/start.sh
redis:
  image: redis
  expose:
    - "6379"
web:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - app
  # volumes:
    # - data-volume:/app
