version: "3"
services:

  getit:
    build: .
    # image: nyulibraries/salon
    environment:
      - REDIS_ADDRESS=http://redis_getit:6379
      - APP_NAME=getit
    env_file:
      - secrets.env
    expose:
      - "8080"
    command: "./scripts/start.sh getit production"
    depends_on:
      - redis_getit
    deploy:
      mode: replicated
      replicas: 2

  arch:
    build: .
    # image: nyulibraries/salon
    environment:
      - REDIS_ADDRESS=http://redis_arch:6379
      - APP_NAME=arch
    env_file:
      - secrets.env
    expose:
      - "8080"
    volumes:
      - public-volume:/app/public
    command: "./scripts/start.sh arch production"
    depends_on:
      - redis_arch
    deploy:
      mode: replicated
      replicas: 2

  redis_getit:
    image: nyulibraries/salon_redis
    expose:
      - "6379"

  redis_arch:
    image: nyulibraries/salon_redis
    expose:
      - "6379"

  nginx:
    build: ./nginx
    # image: nyulibraries/salon_nginx
    ports:
      - "80:80"
    volumes:
      - public-volume:/app/public
    depends_on:
      - arch
      - getit
    deploy:
      mode: replicated
      replicas: 6

volumes:
  public-volume:
