app:
  build: .
  volumes:
    - .:/salon
  links:
    - redis:redishost
  ports:
    - "8080:8080"
  volumes:
    - data-volume:/app
redis:
  image: redis
  expose:
    - "6379"
web:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - app
  volumes:
    - data-volume:/app
