swagger: "2.0"
info:
  description: "This is a simple permalinks application. It can create and serve persistent links with lightening fast speeds."
  version: "1.0.0"
  title: "Salon"
  termsOfService: "https://github.com/NYULibraries/salon#salon"
  contact:
    email: "lib-webservices@nyu.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "nyu-salon.herokuapp.com"
tags:
- name: "persistent links"
  description: "Use and generate persistent links"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/NYULibraries/salon"
schemes:
- "http"
paths:
  /{id}:
    get:
      tags:
      - "persistent links"
      summary: "Use a persistent link"
      description: ""
      consumes:
      - "text/html"
      produces:
      - "text/html"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of persistent link to redirect to"
        required: true
        type: "string"
        x-example: "abc"
      responses:
        302:
          description: "Link found – redirected to URL"
        400:
          description: "Identifier not found"
  /:
    post:
      tags:
      - "persistent links"
      summary: "Create persistent link(s)"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "List of persistent links to be created, represented as a JSON object whose keys are IDs and whose values are their respective URLs"
        required: true
        schema:
          $ref: "#/definitions/PersistentLink"
      responses:
        200:
          description: "Success - persistent link(s) created"
          schema:
            type: object
        400:
          description: "Bad request - check your JSON formatting"
          schema:
            type: object
        401:
          description: "Unauthorized - invalid API key"
          schema:
            type: object
      security:
      - api_key: []
  /reset:
    post:
      tags:
      - "persistent links"
      summary: "Destroy existing links after creating new persistent link(s)"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "List of persistent links to be created, represented as a JSON object whose keys are IDs and whose values are their respective URLs"
        required: true
        schema:
          $ref: "#/definitions/PersistentLink"
      responses:
        200:
          description: "Success - persistent link(s) created"
          schema:
            type: object
        400:
          description: "Bad request - check your JSON formatting"
          schema:
            type: object
        401:
          description: "Unauthorized - invalid API key"
          schema:
            type: object
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "Auth"
    in: "header"
definitions:
  PersistentLink:
    type: "object"
    additionalProperties:
      type: "string"
    example:
      123: "http://example.com"
      abc: "http://library.nyu.edu"
externalDocs:
  description: "Find out more about Salon"
  url: "https://github.com/NYULibraries/salon"
