# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/salon.tar
            - /caches/salon_test.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/salon.tar | true
            docker load -i /caches/salon_test.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=salon -t nyulibraries/salon .
            docker build --cache-from=salon_test -t nyulibraries/salon_test -f Dockerfile.test .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/salon.tar nyulibraries/salon
            docker save -o /caches/salon_test.tar nyulibraries/salon_test
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/salon.tar
            - /caches/salon_test.tar
      - run:
          name: Run tests
          command: |
            touch secrets.env
            docker-compose run test rake
      - run:
          name: Deploy docker image
          command: |
            docker tag nyulibraries/salon nyulibraries/salon:${CIRCLE_BRANCH//\//_}
            docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
            docker push nyulibraries/salon:${CIRCLE_BRANCH//\//_}
