docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
  working_directory: ~/app

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build

test: &test
  run:
    name: Test
    command: |
      touch secrets.env
      docker-compose run test rake

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker tag salon_arch nyulibraries/salon:${BRANCH_NO_SLASH}
      docker tag nyulibraries/salon:${BRANCH_NO_SLASH} nyulibraries/salon:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
      docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      docker push nyulibraries/salon:${BRANCH_NO_SLASH}
      docker push nyulibraries/salon:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

version: 2
jobs:
  test-and-build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *build_docker
      - <<: *test
      - <<: *push_docker

  deploy-dev:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Deploy into staging via Jenkins
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            curl -u $JENKINS_STAGE_USERNAME:$JENKINS_STAGE_API_KEY -X POST https://jenkinsapi-dev.library.nyu.edu/job/Salon%20Development%20Deploy/build/api --data-urlencode json="{\"parameter\": [{\"name\":\"TAG\", \"value\":\"${BRANCH_NO_SLASH}-${CIRCLE_SHA1}\"}]}"

  deploy-prod:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Deploy into production via Jenkins
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            curl -u $JENKINS_PROD_USERNAME:$JENKINS_PROD_API_KEY -X POST https://jenkinsapi.library.nyu.edu/job/Salon%20Production%20Deploy/build/api --data-urlencode json="{\"parameter\": [{\"name\":\"TAG\", \"value\":\"${BRANCH_NO_SLASH}-${CIRCLE_SHA1}\"}]}"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-and-build-image
      - deploy-dev:
          requires:
              - test-and-build-image
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
              - test-and-build-image
          filters:
            branches:
              only: master
